### ISSUE TITLE
Héritage css

### ISSUE THREAD

**Issue by AurianeBispels** [FrancoisCapon/TheWeasyPrintMatrixRobotsProject#2]
Bonjour,
Serait-il possible de faire en sorte que lorsque l'on souhaite écraser le contenu d'une cellule, cela n'écrase que l'information modifiée et non la totalité de la cellule ? 

Exemple :  je modifie le html d'une cellule mais souhaite garder le css, dans le fonctionnement actuel, si l'on ne remet pas le css avec les modifications du html, la cellule écrase l'html et le css.

Merci par avance pour votre retour

**Comment by FrancoisCapon** [comment]
Bonjour,

* Amélioration apportée : 5b0281b

* Ajout d'un exemple d'utilisation sur la matrice `courtbouillon-report` où `html`et `scss` de la page de fin sont choisis indépendamment (valeur 2) pour écraser les fichiers  (valeur 1) de la colonne 15 : 

|   id    | number_row |   segment_row   | number_column |        segment_column        | html | scss | meta |
|---------|------------|-----------------|---------------|------------------------------|------|------|------|
| 9900.15 | 9900       | 9900-page--last | 15            | 15-template-screen-two-pages | 1    | 1    | 0    |
| 9900.2  | 9900       | 9900-page--last | 20            | 20-test-granularity          | 2    | 0    | 0    |
| 9900.21 | 9900       | 9900-page--last | 21            | 21-test-granularity          | 0    | 2    | 0    |

Merci pour le retour :+1:
